# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=10)),
                ('zuping', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('xiaoqu', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('detailed_address', models.CharField(max_length=60)),
                ('host', models.CharField(max_length=20)),
            ],
        ),
    ]
