# Generated by Django 2.0.3 on 2018-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fangyuan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='phone',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
